package org.activiti.cycle;

/**
 * Base class for all actions requiring paremeters (see
 * {@link ParametrizedAction}), where the required HTML form is generated by
 * freemarker. The concrete implementation must return the name of the
 * freemarker template
 * 
 * @author bernd.ruecker@camunda.com
 */
public abstract class ParametrizedFreemakerTemplateAction extends ParametrizedAction {

  public ParametrizedFreemakerTemplateAction() {
  }
  
  public ParametrizedFreemakerTemplateAction(RepositoryArtifact artifact) {
    super(artifact);
  }

  public String getFormAsHtml() {
    // TODO: Implement creation of form with freemarker
    getFreemarkerTemplateUrl();
    return null;
  }
  
  public abstract String getFreemarkerTemplateUrl();
}
